/**
 * A2UI v0.9 Protocol Types
 */

// Component Types
export type {
  ComponentType,
  A2UIComponent,
  TypedA2UIComponent,
  ComponentProperties,
} from './components.js'

// Protocol Types
export type {
  MessageType,
  BaseMessage,
  CreateSurfaceMessage,
  UpdateComponentsMessage,
  ComponentUpdate,
  UpdateDataModelMessage,
  DataUpdate,
  DeleteSurfaceMessage,
  UserActionMessage,
  ErrorMessage,
  PingMessage,
  PongMessage,
  A2UIMessage,
} from './protocol.js'

// Type Guards
export {
  isCreateSurfaceMessage,
  isUpdateComponentsMessage,
  isUpdateDataModelMessage,
  isDeleteSurfaceMessage,
  isUserActionMessage,
  isClientActionMessage,
  isClientActionResponseMessage,
  isErrorMessage,
  isPingMessage,
  isPongMessage,
} from './protocol.js'

// Client Action Types (Issue #45)
export type {
  ClientActionType,
  ClientActionMessage,
  ClientActionResponseMessage,
  PermissionType,
  NavigateAction,
  GoBackAction,
  GoForwardAction,
  RefreshAction,
  ScrollToAction,
  ShowToastAction,
  ShowModalAction,
  CloseModalAction,
  ShowDialogAction,
  CloseDialogAction,
  ShowNotificationAction,
  CopyToClipboardAction,
  DownloadFileAction,
  UploadFileAction,
  ShareContentAction,
  PrintPageAction,
  SetLocalStorageAction,
  GetLocalStorageAction,
  RemoveLocalStorageAction,
  ClearLocalStorageAction,
  RequestPermissionAction,
  GetUserMediaAction,
  VibrateAction,
  OpenCameraAction,
  OpenGalleryAction,
  TrackEventAction,
  TrackPageViewAction,
  SetUserPropertyAction,
  OpenUrlAction,
  SendEmailAction,
  MakePhoneCallAction,
  OpenMapAction,
  SpecificClientAction,
} from './client-action-messages.js'

export {
  isClientActionMessage as isClientActionMessageStrict,
  isClientActionResponseMessage as isClientActionResponseMessageStrict,
} from './client-action-messages.js'

// AI Metadata State Types (Issue #28)
export type {
  TranscriptSegment,
  TranscriptMetadata,
  SummaryType,
  SummaryMetadata,
  TopicCategory,
  Topic,
  TopicMetadata,
  HighlightType,
  Highlight,
  HighlightMetadata,
  Chapter,
  ChapterMetadata,
  SentimentType,
  SentimentScore,
  SentimentTimestamp,
  EmotionDetection,
  SentimentMetadata,
  AIMetadataProcessingState,
  AIMetadataState,
} from './ai-metadata-state.js'

// AI Metadata Type Guards
export {
  isTranscriptMetadata,
  isSummaryMetadata,
  isTopicMetadata,
  isHighlightMetadata,
  isChapterMetadata,
  isSentimentMetadata,
  isAIMetadataState,
} from './ai-metadata-state.js'

// File Upload Component Types (Issue #43)
export type {
  FileMetadata,
  UploadState,
  FileUploadProperties,
  FileValidationResult,
  FileUploadComponent,
} from './file-upload-components.js'

export {
  validateFile,
  validateFiles,
  sanitizeFileName,
  isValidFileName,
  formatFileSize,
  DEFAULT_FILE_UPLOAD_PROPERTIES,
} from './file-upload-components.js'

// File Upload Message Types (Issue #43)
export type {
  FileInfo,
  FileUploadStartMessage,
  FileUploadProgressMessage,
  FileUploadCompleteMessage,
  FileUploadErrorMessage,
  FileUploadCancelMessage,
  FileDeleteMessage,
  FileDeleteCompleteMessage,
  FileUploadMessage,
} from './file-upload-messages.js'

export {
  isFileUploadStartMessage,
  isFileUploadProgressMessage,
  isFileUploadCompleteMessage,
  isFileUploadErrorMessage,
  isFileUploadCancelMessage,
  isFileDeleteMessage,
  isFileDeleteCompleteMessage,
  createFileUploadStartMessage,
  createFileUploadProgressMessage,
  createFileUploadCompleteMessage,
  createFileUploadErrorMessage,
} from './file-upload-messages.js'

// Progressive Rendering Message Types (Issue #53)
export type {
  ProgressiveRenderStartMessage,
  ProgressiveRenderChunkMessage,
  ProgressiveRenderCompleteMessage,
  ProgressiveRenderErrorMessage,
  ProgressiveRenderProgressMessage,
  ExtendedMessageType,
  ProgressiveRenderMessage,
  ExtendedA2UIMessage,
} from './progressive-render-messages.js'

export {
  isProgressiveRenderStartMessage,
  isProgressiveRenderChunkMessage,
  isProgressiveRenderCompleteMessage,
  isProgressiveRenderErrorMessage,
  isProgressiveRenderProgressMessage,
  isProgressiveRenderMessage,
} from './progressive-render-messages.js'

// Notification Component Types (Issue #49)
export type {
  NotificationType,
  NotificationPriority,
  NotificationPosition,
  NotificationFilterType,
  NotificationGroupBy,
  BadgePosition,
  NotificationCategory,
  NotificationAction,
  NotificationRichContent,
  NotificationCenterProperties,
  NotificationCenterComponent,
  NotificationItemProperties,
  NotificationItemComponent,
  NotificationBadgeProperties,
  NotificationBadgeComponent,
  NotificationState,
  NotificationSettings,
} from './notification-components.js'

export {
  DEFAULT_NOTIFICATION_CENTER_PROPERTIES,
  DEFAULT_NOTIFICATION_BADGE_PROPERTIES,
  isNotificationCenterComponent,
  isNotificationItemComponent,
  isNotificationBadgeComponent,
  createNotificationCenter,
  createNotificationItem,
  createNotificationBadge,
  formatNotificationTimestamp,
  getNotificationIcon,
  getNotificationColor,
} from './notification-components.js'

// Notification Message Types (Issue #49)
export type {
  NotificationData,
  NotificationUpdateData,
  NotificationFilters,
  NotificationListItem,
  NotificationCreateMessage,
  NotificationCreatedMessage,
  NotificationUpdateMessage,
  NotificationUpdatedMessage,
  NotificationDeleteMessage,
  NotificationDeletedMessage,
  NotificationMarkAllReadMessage,
  NotificationAllMarkedReadMessage,
  NotificationDeleteAllMessage,
  NotificationAllDeletedMessage,
  NotificationActionMessage,
  NotificationListRequestMessage,
  NotificationListResponseMessage,
  NotificationGetRequestMessage,
  NotificationGetResponseMessage,
  NotificationSettingsUpdateMessage,
  NotificationSettingsUpdatedMessage,
  NotificationCountMessage,
  NotificationSubscribeMessage,
  NotificationUnsubscribeMessage,
  NotificationErrorMessage,
  NotificationMessage,
} from './notification-messages.js'

export {
  isNotificationCreateMessage,
  isNotificationCreatedMessage,
  isNotificationUpdateMessage,
  isNotificationUpdatedMessage,
  isNotificationDeleteMessage,
  isNotificationDeletedMessage,
  isNotificationMarkAllReadMessage,
  isNotificationAllMarkedReadMessage,
  isNotificationDeleteAllMessage,
  isNotificationAllDeletedMessage,
  isNotificationActionMessage,
  isNotificationListRequestMessage,
  isNotificationListResponseMessage,
  isNotificationGetRequestMessage,
  isNotificationGetResponseMessage,
  isNotificationSettingsUpdateMessage,
  isNotificationSettingsUpdatedMessage,
  isNotificationCountMessage,
  isNotificationSubscribeMessage,
  isNotificationUnsubscribeMessage,
  isNotificationErrorMessage,
  createNotificationCreateMessage,
  createNotificationUpdateMessage,
  createNotificationDeleteMessage,
  createNotificationListRequestMessage,
  createNotificationActionMessage,
} from './notification-messages.js'

// Billing & Subscription Component Types (Issue #50)
export type {
  SubscriptionPlan,
  BillingHistoryItem,
  PaymentMethodType,
  PaymentMethodInfo,
  UsageMetric,
  InvoiceLineItem,
  InvoiceData,
  BillingAddress,
  BillingAddressField,
  SubscriptionPlanComponent,
  BillingHistoryComponent,
  PaymentMethodComponent,
  UsageMeterComponent,
  InvoiceViewerComponent,
  BillingAddressComponent,
  BillingComponent,
} from './billing-components.js'

export {
  isSubscriptionPlanComponent,
  isBillingHistoryComponent,
  isPaymentMethodComponent,
  isUsageMeterComponent,
  isInvoiceViewerComponent,
  isBillingAddressComponent,
} from './billing-components.js'

// Billing & Subscription Message Types (Issue #50)
export type {
  BaseBillingMessage,
  SubscriptionSelectPlanMessage,
  SubscriptionChangePlanMessage,
  SubscriptionCancelMessage,
  SubscriptionResumeMessage,
  SubscriptionUpdatedMessage,
  CardPaymentDetails,
  BankPaymentDetails,
  PayPalPaymentDetails,
  PaymentMethodAddMessage,
  PaymentMethodUpdateMessage,
  PaymentMethodDeleteMessage,
  PaymentMethodSetDefaultMessage,
  PaymentMethodAddedMessage,
  PaymentMethodErrorMessage,
  InvoiceFilters,
  InvoiceSummary,
  InvoiceListRequestMessage,
  InvoiceListResponseMessage,
  InvoiceDownloadMessage,
  InvoiceDownloadedMessage,
  InvoicePayMessage,
  InvoicePaidMessage,
  InvoiceCreatedMessage,
  UsageMetricData,
  UsageUpdateMessage,
  UsageRequestMessage,
  UsageWarningMessage,
  BillingAddressUpdateMessage,
  BillingAddressUpdatedMessage,
  BillingAddressValidationMessage,
  PaymentIntentCreatedMessage,
  PaymentProcessingMessage,
  PaymentSuccessMessage,
  PaymentFailedMessage,
  SubscriptionMessage,
  PaymentMethodMessage,
  InvoiceMessage,
  UsageMessage,
  BillingAddressMessage,
  PaymentMessage,
  BillingMessage,
} from './billing-messages.js'

export {
  isSubscriptionSelectPlanMessage,
  isSubscriptionChangePlanMessage,
  isSubscriptionCancelMessage,
  isPaymentMethodAddMessage,
  isInvoiceListRequestMessage,
  isInvoicePayMessage,
  isUsageUpdateMessage,
  isBillingAddressUpdateMessage,
  isPaymentSuccessMessage,
  isPaymentFailedMessage,
} from './billing-messages.js'

// Authentication Component Types (Issue #48)
export type {
  AuthProvider,
  UserField,
  PasswordRequirements,
  PasswordResetStep,
  PasswordResetMethod,
  ProfileLayout,
  TwoFactorMethod,
  TwoFactorStep,
  SessionGrouping,
  AuthLoginFormComponent,
  AuthSignupFormComponent,
  AuthPasswordResetComponent,
  AuthProfileComponent,
  AuthSessionManagerComponent,
  Auth2FAComponent,
  AuthOAuthCallbackComponent,
  AuthComponent,
} from './auth-components.js'

export {
  isAuthLoginFormComponent,
  isAuthSignupFormComponent,
  isAuthPasswordResetComponent,
  isAuthProfileComponent,
  isAuthSessionManagerComponent,
  isAuth2FAComponent,
  isAuthOAuthCallbackComponent,
  isAuthComponent,
  validatePassword,
  validateEmail,
  validateUsername,
  validatePhoneNumber,
} from './auth-components.js'

// Authentication Message Types (Issue #48)
export type {
  AuthUser,
  AuthErrorCode,
  Session,
  OAuthConfig,
  AuthLoginMessage,
  AuthLoginSuccessMessage,
  AuthLoginErrorMessage,
  AuthSignupMessage,
  AuthSignupSuccessMessage,
  AuthSignupErrorMessage,
  AuthPasswordResetRequestMessage,
  AuthPasswordResetRequestSuccessMessage,
  AuthPasswordResetVerifyMessage,
  AuthPasswordResetVerifySuccessMessage,
  AuthPasswordResetCompleteMessage,
  AuthPasswordResetCompleteSuccessMessage,
  AuthPasswordResetErrorMessage,
  AuthProfileUpdateMessage,
  AuthProfileUpdateSuccessMessage,
  AuthProfileUpdateErrorMessage,
  AuthPasswordChangeMessage,
  AuthPasswordChangeSuccessMessage,
  AuthPasswordChangeErrorMessage,
  AuthSessionListMessage,
  AuthSessionListResponseMessage,
  AuthSessionTerminateMessage,
  AuthSessionTerminateSuccessMessage,
  AuthSessionErrorMessage,
  Auth2FASetupMessage,
  Auth2FASetupResponseMessage,
  Auth2FAVerifyMessage,
  Auth2FAVerifySuccessMessage,
  Auth2FADisableMessage,
  Auth2FADisableSuccessMessage,
  Auth2FAErrorMessage,
  AuthOAuthInitiateMessage,
  AuthOAuthInitiateResponseMessage,
  AuthOAuthCallbackMessage,
  AuthOAuthCallbackSuccessMessage,
  AuthOAuthErrorMessage,
  AuthLogoutMessage,
  AuthLogoutSuccessMessage,
  AuthLogoutErrorMessage,
  AuthEmailVerificationRequestMessage,
  AuthEmailVerificationVerifyMessage,
  AuthEmailVerificationSuccessMessage,
  AuthTokenRefreshMessage,
  AuthTokenRefreshSuccessMessage,
  AuthMessage,
} from './auth-messages.js'

export {
  isAuthLoginMessage,
  isAuthLoginSuccessMessage,
  isAuthLoginErrorMessage,
  isAuthSignupMessage,
  isAuthSignupSuccessMessage,
  isAuthSignupErrorMessage,
  isAuthPasswordResetRequestMessage,
  isAuthPasswordResetVerifyMessage,
  isAuthPasswordResetCompleteMessage,
  isAuthProfileUpdateMessage,
  isAuthPasswordChangeMessage,
  isAuthSessionListMessage,
  isAuthSessionTerminateMessage,
  isAuth2FASetupMessage,
  isAuth2FAVerifyMessage,
  isAuth2FADisableMessage,
  isAuthOAuthInitiateMessage,
  isAuthOAuthCallbackMessage,
  isAuthLogoutMessage,
  isAuthTokenRefreshMessage,
} from './auth-messages.js'
